# Generated by Django 4.2.27 on 2025-12-20 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro de série')),
                ('cpusn', models.CharField(blank=True, max_length=50, verbose_name='Numéro de série CPU')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='Modèle')),
                ('firmware', models.CharField(blank=True, max_length=100, verbose_name='Firmware')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='Adresse MAC')),
                ('user_capacity', models.IntegerField(default=3000, verbose_name='Capacité utilisateurs')),
                ('fp_capacity', models.IntegerField(default=3000, verbose_name='Capacité empreintes')),
                ('card_capacity', models.IntegerField(default=3000, verbose_name='Capacité cartes')),
                ('log_capacity', models.IntegerField(default=100000, verbose_name='Capacité logs')),
                ('used_users', models.IntegerField(default=0, verbose_name='Utilisateurs utilisés')),
                ('used_fp', models.IntegerField(default=0, verbose_name='Empreintes utilisées')),
                ('used_cards', models.IntegerField(default=0, verbose_name='Cartes utilisées')),
                ('used_logs', models.IntegerField(default=0, verbose_name='Logs utilisés')),
                ('fp_algo', models.CharField(blank=True, max_length=50, verbose_name='Algorithme empreinte')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_whitelisted', models.BooleanField(default=True, verbose_name='En liste blanche')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminaux',
                'db_table': 'tm20_terminals',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='CommandQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50, verbose_name='Commande')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('success', 'Succès'), ('failed', 'Échec'), ('timeout', 'Timeout')], default='pending', max_length=20, verbose_name='Statut')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='Réponse')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Commande en attente',
                'verbose_name_plural': 'Commandes en attente',
                'db_table': 'tm20_command_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollid', models.IntegerField(db_index=True, verbose_name="ID d'enrôlement")),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('admin', models.IntegerField(choices=[(0, 'Utilisateur normal'), (1, 'Administrateur'), (2, 'Super utilisateur')], default=0, verbose_name='Niveau admin')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('weekzone', models.IntegerField(default=1, verbose_name='Zone semaine 1')),
                ('weekzone2', models.IntegerField(default=1, verbose_name='Zone semaine 2')),
                ('weekzone3', models.IntegerField(default=1, verbose_name='Zone semaine 3')),
                ('weekzone4', models.IntegerField(default=1, verbose_name='Zone semaine 4')),
                ('group', models.IntegerField(default=0, verbose_name='Groupe')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='Date de début validité')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin validité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='devices.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Utilisateur biométrique',
                'verbose_name_plural': 'Utilisateurs biométriques',
                'db_table': 'tm20_biometric_users',
                'ordering': ['enrollid'],
                'unique_together': {('terminal', 'enrollid')},
            },
        ),
        migrations.CreateModel(
            name='BiometricCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backupnum', models.IntegerField(choices=[(0, 'Empreinte 1'), (1, 'Empreinte 2'), (2, 'Empreinte 3'), (3, 'Empreinte 4'), (4, 'Empreinte 5'), (5, 'Empreinte 6'), (6, 'Empreinte 7'), (7, 'Empreinte 8'), (8, 'Empreinte 9'), (9, 'Empreinte 10'), (10, 'Mot de passe'), (11, 'Carte RFID'), (20, 'Visage statique 1'), (21, 'Visage statique 2'), (22, 'Visage statique 3'), (23, 'Visage statique 4'), (24, 'Visage statique 5'), (25, 'Visage statique 6'), (26, 'Visage statique 7'), (27, 'Visage statique 8'), (30, 'Paume 1'), (31, 'Paume 2'), (32, 'Paume 3'), (33, 'Paume 4'), (34, 'Paume 5'), (35, 'Paume 6'), (36, 'Paume 7'), (37, 'Paume 8'), (50, 'Photo')], verbose_name='Type de credential')),
                ('record', models.TextField(verbose_name='Données (base64 ou valeur)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='devices.biometricuser', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Credential biométrique',
                'verbose_name_plural': 'Credentials biométriques',
                'db_table': 'tm20_biometric_credentials',
                'unique_together': {('user', 'backupnum')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollid', models.IntegerField(db_index=True, verbose_name="ID d'enrôlement")),
                ('time', models.DateTimeField(db_index=True, verbose_name='Date/heure pointage')),
                ('mode', models.IntegerField(choices=[(0, 'Empreinte'), (1, 'Carte'), (2, 'Mot de passe'), (3, 'Carte'), (8, 'Visage'), (13, 'QR Code')], default=0, verbose_name='Mode de vérification')),
                ('inout', models.IntegerField(choices=[(0, 'Entrée'), (1, 'Sortie')], default=0, verbose_name='Entrée/Sortie')),
                ('event', models.IntegerField(choices=[(0, 'Normal'), (1, 'F1'), (2, 'F2'), (3, 'F3'), (4, 'F4')], default=0, verbose_name='Événement')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Température')),
                ('verifymode', models.IntegerField(blank=True, null=True, verbose_name='Mode vérification détaillé')),
                ('image', models.TextField(blank=True, verbose_name='Image (base64)')),
                ('log_index', models.IntegerField(blank=True, null=True, verbose_name='Index du log')),
                ('raw_payload', models.JSONField(default=dict, verbose_name='Payload brut')),
                ('access_granted', models.BooleanField(default=True, verbose_name='Accès accordé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.terminal', verbose_name='Terminal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='devices.biometricuser', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log de pointage',
                'verbose_name_plural': 'Logs de pointage',
                'db_table': 'tm20_attendance_logs',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['terminal', 'time'], name='tm20_attend_termina_6dfe1c_idx'), models.Index(fields=['enrollid', 'time'], name='tm20_attend_enrolli_6a7de1_idx')],
            },
        ),
    ]
