# Generated by Django 4.2.27 on 2025-12-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la configuration')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('base_url', models.URLField(verbose_name="URL de base de l'API")),
                ('users_endpoint', models.CharField(blank=True, help_text='Ex: /api/users', max_length=255, verbose_name='Endpoint pour récupérer les utilisateurs')),
                ('attendance_endpoint', models.CharField(blank=True, help_text='Ex: /api/attendance', max_length=255, verbose_name='Endpoint pour envoyer les pointages')),
                ('auth_type', models.CharField(choices=[('none', 'Aucune'), ('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('basic', 'Basic Auth')], default='bearer', max_length=20, verbose_name="Type d'authentification")),
                ('auth_token', models.CharField(blank=True, max_length=500, verbose_name="Token/Clé d'authentification")),
                ('auth_header_name', models.CharField(default='Authorization', max_length=100, verbose_name="Nom du header d'authentification")),
                ('extra_headers', models.JSONField(blank=True, default=dict, help_text='Format JSON: {"key": "value"}', verbose_name='Headers supplémentaires')),
                ('sync_interval_minutes', models.IntegerField(default=15, help_text="Intervalle pour l'envoi automatique des pointages", verbose_name='Intervalle de synchronisation (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('timeout_seconds', models.IntegerField(default=30, verbose_name='Timeout (secondes)')),
                ('retry_attempts', models.IntegerField(default=3, verbose_name="Nombre de tentatives en cas d'échec")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration service tiers',
                'verbose_name_plural': 'Configurations services tiers',
                'db_table': 'tm20_third_party_configs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='sync_attempts',
            field=models.IntegerField(default=0, verbose_name='Tentatives de synchronisation'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='sync_error',
            field=models.TextField(blank=True, verbose_name='Erreur de synchronisation'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec')], db_index=True, default='pending', max_length=20, verbose_name='Statut de synchronisation'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de synchronisation'),
        ),
        migrations.CreateModel(
            name='TerminalThirdPartyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sync_users', models.BooleanField(default=True, verbose_name='Synchroniser les utilisateurs')),
                ('sync_attendance', models.BooleanField(default=True, verbose_name='Synchroniser les pointages')),
                ('last_user_sync', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchro utilisateurs')),
                ('last_attendance_sync', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchro pointages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_mappings', to='devices.thirdpartyconfig', verbose_name='Configuration')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_mappings', to='devices.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Mapping Terminal-Service tiers',
                'verbose_name_plural': 'Mappings Terminal-Services tiers',
                'db_table': 'tm20_terminal_third_party_mappings',
                'ordering': ['terminal', 'config'],
                'unique_together': {('terminal', 'config')},
            },
        ),
        migrations.CreateModel(
            name='TerminalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Horaire standard, Horaire été', max_length=100, verbose_name="Nom de l'horaire")),
                ('weekday', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('check_in_time', models.TimeField(verbose_name="Heure d'arrivée")),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='Début de pause')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='Fin de pause')),
                ('check_out_time', models.TimeField(verbose_name='Heure de sortie')),
                ('tolerance_minutes', models.IntegerField(default=15, help_text='Tolérance de retard acceptable', verbose_name='Tolérance (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Effectif à partir du')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name="Effectif jusqu'au")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Horaire de terminal',
                'verbose_name_plural': 'Horaires de terminaux',
                'db_table': 'tm20_terminal_schedules',
                'ordering': ['terminal', 'weekday', 'check_in_time'],
                'indexes': [models.Index(fields=['terminal', 'weekday', 'is_active'], name='tm20_termin_termina_4fa1d5_idx')],
            },
        ),
    ]
