# Generated by Django 4.2.27 on 2026-01-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_thirdpartyconfig_attendancelog_sync_attempts_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biometricuser',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID utilisateur provenant du système source (RH, ERP, etc.)', max_length=100, verbose_name='ID externe'),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation'),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Données supplémentaires provenant du service tiers', verbose_name='Métadonnées'),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='source_config',
            field=models.ForeignKey(blank=True, help_text="Configuration du service tiers d'où provient l'utilisateur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='devices.thirdpartyconfig', verbose_name='Source de synchronisation'),
        ),
        migrations.AddField(
            model_name='biometricuser',
            name='sync_status',
            field=models.CharField(choices=[('local', 'Créé localement'), ('synced', 'Synchronisé depuis service tiers'), ('pending_sync', 'En attente de synchronisation vers terminal'), ('synced_to_terminal', 'Synchronisé vers terminal'), ('error', 'Erreur de synchronisation')], db_index=True, default='local', max_length=20, verbose_name='Statut de synchronisation'),
        ),
        migrations.AlterField(
            model_name='biometricuser',
            name='enrollid',
            field=models.IntegerField(db_index=True, help_text='ID interne utilisé par le terminal biométrique', verbose_name="ID d'enrôlement"),
        ),
        migrations.AlterField(
            model_name='biometricuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom complet'),
        ),
        migrations.AddIndex(
            model_name='biometricuser',
            index=models.Index(fields=['terminal', 'external_id'], name='tm20_biomet_termina_b1ebff_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricuser',
            index=models.Index(fields=['terminal', 'sync_status'], name='tm20_biomet_termina_cf70c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='biometricuser',
            constraint=models.UniqueConstraint(fields=('terminal', 'enrollid'), name='unique_terminal_enrollid'),
        ),
        migrations.AddConstraint(
            model_name='biometricuser',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('terminal', 'external_id'), name='unique_terminal_external_id'),
        ),
    ]
