# Generated by Django 4.2.30 on 2026-09-28 15:00

import logging

from django.db import migrations, models
from django.db.models import Count, Min

logger = logging.getLogger('devices.migrations')


def drop_duplicate_logs(apps, schema_editor):
    """Supprime les doublons de pointages avant la pose de la contrainte.

    Jusqu'ici le service de pointage n'avait aucune deduplication et appelait
    `bulk_create()` sans `ignore_conflicts` : chaque retransmission d'un lot
    par un terminal (reponse serveur perdue) creait autant de lignes
    identiques. Poser la contrainte d'unicite sur une base existante echouerait
    donc par IntegrityError, interrompant le deploiement au milieu.

    On conserve la ligne la plus ancienne de chaque groupe (`Min('id')`) :
    c'est celle qui porte le `log_index` de la premiere reception.
    """
    AttendanceLog = apps.get_model('devices', 'AttendanceLog')

    groups = list(
        AttendanceLog.objects
        .values('terminal_id', 'enrollid', 'time', 'event')
        .annotate(n=Count('id'), keep=Min('id'))
        .filter(n__gt=1)
    )
    if not groups:
        return

    deleted = 0
    for group in groups:
        count, _ = (
            AttendanceLog.objects
            .filter(
                terminal_id=group['terminal_id'],
                enrollid=group['enrollid'],
                time=group['time'],
                event=group['event'],
            )
            .exclude(id=group['keep'])
            .delete()
        )
        deleted += count

    logger.warning(
        f"{deleted} pointage(s) en double supprime(s) sur {len(groups)} groupe(s) "
        f"avant la pose de uniq_attendance_log_per_terminal_event"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_repair_terminal_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Empreinte'), (1, 'Empreinte'), (2, 'Mot de passe'), (3, 'Carte'), (8, 'Visage'), (13, 'QR Code')], default=0, verbose_name='Mode de vérification'),
        ),
        # Le nettoyage DOIT preceder la contrainte : voir drop_duplicate_logs.
        migrations.RunPython(drop_duplicate_logs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='attendancelog',
            constraint=models.UniqueConstraint(fields=('terminal', 'enrollid', 'time', 'event'), name='uniq_attendance_log_per_terminal_event'),
        ),
    ]
