# Generated by Django 4.2.30 on 2026-09-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_attendancelog_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Relevée à chaque enregistrement (`reg`) du terminal.', null=True, verbose_name='Dernière adresse IP'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='location',
            field=models.CharField(blank=True, help_text='Site, bâtiment ou salle où le terminal est installé.', max_length=150, verbose_name='Emplacement'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='name',
            field=models.CharField(blank=True, help_text='Libellé lisible, ex: « Entrée principale ». À défaut, le n° de série est affiché.', max_length=100, verbose_name='Nom'),
        ),
    ]
